// $Id$

#ifndef EVCPE_METHOD_H_
#define EVCPE_METHOD_H_

#include <time.h>

#include "data.h"

enum evcpe_method_type {
	EVCPE_UNKNOWN_METHOD,
	EVCPE_GET_RPC_METHODS,
	EVCPE_SET_PARAMETER_VALUES,
	EVCPE_GET_PARAMETER_VALUES,
	EVCPE_GET_PARAMETER_NAMES,
	EVCPE_SET_PARAMETER_ATTRIBUTES,
	EVCPE_GET_PARAMETER_ATTRIBUTES,
	EVCPE_ADD_OBJECT,
	EVCPE_DELETE_OBJECT,
	EVCPE_REBOOT,
	EVCPE_DOWNLOAD,
	EVCPE_UPLOAD,
	EVCPE_FACTORY_RESET,
	EVCPE_GET_QUEUED_TRANSFERS,
	EVCPE_GET_ALL_QUEUED_TRANSFERS,
	EVCPE_SCHEDULE_INFORM,
	EVCPE_SET_VOUCHERS,
	EVCPE_GET_OPTIONS,
	EVCPE_INFORM,
	EVCPE_TRANSFER_COMPLETE,
	EVCPE_AUTONOMOUS_TRANSFER_COMPLETE,
	EVCPE_REQUEST_DOWNLOAD,
	EVCPE_KICKED
};

const char *evcpe_method_type_to_str(enum evcpe_method_type type);

#endif /* EVCPE_METHOD_H_ */
